name: kirihare
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.9+52


environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  change_app_package_name: ^1.1.0
  dio: ^5.3.2
  fbroadcast: ^2.0.0
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  firebase_messaging: ^14.6.5
  cloud_firestore:

  flutter_datetime_picker_plus: ^2.0.1
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.2
  google_fonts: ^6.1.0
  intl: ^0.18.0
  linkwell: ^2.0.6
  logger: ^2.0.1
  modal_progress_hud_nsn: ^0.4.0
  permission_handler: ^11.1.0
  shared_preferences: ^2.2.0
  soundpool: ^2.3.0
  url_launcher: ^6.1.12
  web_socket_channel: ^2.4.0
  json_annotation: ^4.8.1
  soundpool_web: ^2.2.0
  scrollable_positioned_list: ^0.3.8
  pin_code_fields: ^8.0.1
  flutter_local_notifications: ^15.1.0+1
  universal_html: ^2.2.0
  csslib: ^1.0.0
  intl_phone_field: # lib custom not edit
    git: 
      url: "https://github.com/otyhu12/intl_phone_field.git"
  quick_notify: ^0.2.1

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/login.png
    - assets/images/how_to_use.png
    - assets/images/key.png
    - assets/images/inquiry.png
    - assets/images/mental_health_consultation.png
    - assets/images/stretching_mind.png
    - assets/images/self_check_on_mind.png
    - assets/images/usage_history.png
    - assets/images/default_img.png
    - assets/images/stress_check.png
    - assets/images/family_relationship_check.png
    - assets/images/large_person_adhd_check.png
    - assets/images/depression_check.png
    - assets/images/self_care.png
    - assets/images/mindfulness.png
    - assets/images/autogenic_training.png
    - assets/images/column_method.png
    - assets/sound/beep.wav
    - assets/images/avatar.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/launch_icon.png"